[GoodMorning]
enable = true

# 问好黑名单
blacklist_command_set = ["加入问候语黑名单"]
blacklist_command_get = ["问候语黑名单"]
blacklist_command_delete = ["删除问候语黑名单"]
# 天气
weather_command_set = ["问候语天气"]
weather_command_get = ["问候语天气列表"]
weather_command_delete = ["删除问候语天气"]

hello_texts = [
    [
        "腾里云在线接单！祝各位老板生意兴隆。"
    ],
    [
        "事业腾飞正当时, 商祺祝福添吉祥。"
    ],
    [
        "您的事业蒸蒸日上, 商祺相伴共创辉煌。"
    ],
    [
        "笔落惊风雨, 字成祝商祺。",
        "愿君展宏图, 事业步步升。"
    ],
    [
        "祝您生活愉快，事业蒸蒸日上！"
    ]
]